


USE ROLE NYCTRANSFORM;
USE WAREHOUSE NYC_TAXI_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS YELLOW_TAXI_TRIPS (
    VENDORID NUMBER(38,0),
    TPEP_PICKUP_DATETIME TIMESTAMP_NTZ(6),
    TPEP_DROPOFF_DATETIME TIMESTAMP_NTZ(6),
    PASSENGER_COUNT FLOAT,
    TRIP_DISTANCE FLOAT,
    RATECODEID FLOAT,
    STORE_AND_FWD_FLAG VARCHAR(16777216),
    PULOCATIONID NUMBER(38,0),
    DOLOCATIONID NUMBER(38,0),
    PAYMENT_TYPE NUMBER(38,0),
    FARE_AMOUNT FLOAT,
    EXTRA FLOAT,
    MTA_TAX FLOAT,
    TIP_AMOUNT FLOAT,
    TOLLS_AMOUNT FLOAT,
    IMPROVEMENT_SURCHARGE FLOAT,
    TOTAL_AMOUNT FLOAT,
    CONGESTION_SURCHARGE FLOAT,
    AIRPORT_FEE FLOAT
);
