USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
GRANT OPERATE ON WAREHOUSE NYC_TAXI_WH TO NYCTRANSFORM;

CREATE USER IF NOT EXISTS NYCDBT
    PASSWORD = {?}
    LOGIN_NAME = 'NYCDBT'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = 'NYCTRANSFORM'
    DEFAULT_WAREHOUSE = 'NYC_TAXI_DB'
    DEFAULT_NAMESPACE = 'NYC_TAXI_DB.RAW';

CREATE DATABASE IF NOT EXISTS NYC_TAXI_DB;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.RAW;