USE ROLE ACCOUNTADMIN;

-- Accorder le rôle NYCTRANSFORM à ton utilisateur principal
GRANT ROLE NYCTRANSFORM TO USER d4v1dbr34u;

GRANT ALL ON WAREHOUSE NYC_TAXI_WH TO ROLE NYCTRANSFORM;
GRANT ALL ON DATABASE NYC_TAXI_DB to ROLE NYCTRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE NYC_TAXI_DB to ROLE NYCTRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NYC_TAXI_DB to ROLE NYCTRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_DB.RAW to ROLE NYCTRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_DB.RAW to ROLE NYCTRANSFORM;
