USE ROLE NYCTRANSFORM;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_DB
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
GRANT OPERATE ON NYC_TAXI_DB TO NYCTRANSFORM;

CREATE USER IF NOT EXISTS NYCDBT;

CREATE DATABASE IF NOT EXISTS NYC_TAXI_DB;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.RAW;