USE ROLE NYCTRANSFORM;

GRANT ALL ON WAREHOUSE NYC_TAXI_WH TO ROLE NYCTRANSFORM;
GRANT ALL ON DATABASE NYC_TAXI_DB to ROLE NYCTRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE NYC_TAXI_DB to ROLE NYCTRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NYC_TAXI_DB to ROLE NYCTRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_DB.RAW to ROLE NYCTRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_DB.RAW to ROLE NYCTRANSFORM;
